---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: onyx-twitter-sample
    component: mysql
spec:
  ports:
    - port: 3306
      name: sql
  selector:
    component: mysql
  type: LoadBalancer
