---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: onyx-twitter-sample
    component: zookeeper
spec:
  ports:
    - port: 2181
      name: comm
    - port: 2888
      name: in
    - port: 3888
      name: out
    - port: 8181
      name: exhibitor
  selector:
    component: zookeeper
