peer:
  image: peerimage
  environment:
    ONYX_ID: 1
    NPEERS: 8
    MEDIA_DRIVER_JAVA_OPTS: "-server"
    PEER_JAVA_OPTS: "-server"
    TWITTER_CONSUMER_KEY: ""
    TWITTER_CONSUMER_SECRET: ""
    TWITTER_ACCESS_TOKEN: ""
    TWITTER_ACCESS_SECRET: ""
  shm_size: "512mb"
  links:
    - zookeeper:zookeeper
    - mysql:mysql

zookeeper:
  image: 'wurstmeister/zookeeper'
  ports:
    - '2181:2181'

mysql:
  image: 'tutum/mysql'
  ports:
    - '3306:3306'
  environment:
    ON_CREATE_DB: "onyx"
    MYSQL_PASS: "mypass"
