peer:
  image: peerimage
  environment:
    ONYX_ID: 1
    NPEERS: 8
    TWITTER_CONSUMER_KEY: "lIEdXnngvgJ4eWWMFY6R5EMQd"
    TWITTER_CONSUMER_SECRET: "L6ZmWryK3wQL8pej223LxZdwdWQ8SVAyN9OFZglEBGnfqIqaZ0"
    TWITTER_ACCESS_TOKEN: "3191952868-N6VzkTyHXexyxzG3G58T6qWsXLBDEjyyqSwJ9M5"
    TWITTER_ACCESS_SECRET: "AmFKtxYw7bbWcrFFeINSQ26dlrO2nUm0BvZ9mBt043hT2"
  shm_size: "512mb"
  links:
    - zookeeper:zookeeper
    - mysql:mysql

zookeeper:
  image: 'wurstmeister/zookeeper'
  ports:
    - '2181:2181'

mysql:
  image: 'tutum/mysql'
  ports:
    - '3306:3306'
  environment:
    ON_CREATE_DB: "onyx"
    MYSQL_PASS: "mypass"
