---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: bookkeeper
  labels:
    app: onyx-twitter-sample
    component: bookkeeper
spec:
  serviceName: "bookkeeper"
  replicas: 3
  template:
    metadata:
      labels:
        app: onyx-twitter-sample
        component: bookkeeper
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: bookie
          image: onyxplatform/bookkeeper:latest
          env:
          - name: BOOKKEEPER_ZOOKEEPER_CONNECT
            value: zk:2181
          - name: NAMESPACE
          ports:
          - containerPort: 3181
          volumeMounts:
          - name: bpi
            mountPath: /data/index
          - name: bpj
            mountPath: /data/journal
          - name: bpl
            mountPath: /data/ledger
  volumeClaimTemplates:
    - metadata:
        name: bpi
#        annotations:
#          volume.alpha.kubernetes.io/storage-class: anything
        labels:
          component: bookkeeper
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: bpj
#        annotations:
#          volume.alpha.kubernetes.io/storage-class: anything
        labels:
          component: bookkeeper
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: bpl
#        annotations:
#          volume.alpha.kubernetes.io/storage-class: anything
        labels:
          component: bookkeeper
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi


## address bookie{0...N}.bookkeeper.default.svc.cluster.local
### /opt/bookkeeper/bin/bookkeeper shell metaformat -nonInteractive &> /dev/null
