apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: onyx-twitter-sample
    component: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: onyx-twitter-sample
        component: mysql
    spec:
      containers:
        - name: mysql
          image: tutum/mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: ON_CREATE_DB
              value: 'onyx'
            - name: MYSQL_PASS
              value: 'mypass'
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysql -u root -P mypass -e 'show databases;'"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: onyx-twitter-sample
    component: mysql
spec:
  ports:
    - port: 3306
      name: sql
  selector:
    component: mysql
