---
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: bookkeeper
  labels:
    app: onyx-twitter-sample
    component: bookkeeper-bookie
spec:
  ports:
  ports:
    - name: bookie
      port: 3181
      protocol: TCP
  # *.bookeeper.default.svc.cluster.local
  clusterIP: None
  selector:
    component: bookkeeper
