apiVersion: v1
kind: Service
metadata:
  name: bookkeeper
  labels:
    app: onyx-twitter-sample
    component: bookkeeper-bookie
spec:
  ports:
    - name: bookie
      port: 3181
      protocol: TCP
  selector:
    app: onyx-twitter-sample
    component: bookkeeper-bookie
