---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  labels:
    app: onyx-twitter-sample
    component: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    component: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  labels:
    app: onyx-twitter-sample
    component: zookeeper-2
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    component: zookeeper-2
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  labels:
    app: onyx-twitter-sample
    component: zookeeper-3
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    component: zookeeper-3